### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by khalifeserge** [minorua/TileLayerPlugin#29]
Zooming rapidly in and out crashes QGIS 2.18.9 with the following error:
2017-06-22T15:31:40	1	Traceback (most recent call last):
			  File "/.qgis2/python/plugins\TileLayerPlugin\tilelayer.py", line 268, in draw
			    files = self.fetchFiles(urls, renderContext)
			  File "/.qgis2/python/plugins\TileLayerPlugin\tilelayer.py", line 589, in fetchFiles
			    downloader.abort(False)
			  File "/.qgis2/python/plugins\TileLayerPlugin\downloader.py", line 131, in abort
			    for reply in self.requestingReplies.itervalues():
			RuntimeError: dictionary changed size during iteration

**Comment by Andre-J** [comment]
Same here, since QGIS version 2.18.5 up to current 2.18.11 on Windows 7. I get an empty yellow bar above the canvas (where you can usually read error messages). In most cases QGIS crashes afterwards.

**Comment by martinmbaihaqi** [comment]
How solve this problem? Need help

**Comment by minorua** [comment]
@martinmbaihaqi I recommend using the XYZ tile layer natively supported by QGIS 2.18.

https://www.qgis.org/en/site/forusers/visualchangelog218/index.html#feature-native-support-of-xyz-tile-layers

**Comment by Andre-J** [comment]
Unfortunately, the XYZ tile layer is not half as good as your plugin: No support for the file:/// protocol, and no chance to set a maximum zoom level after which the tiles get magnified.
