### ISSUE TITLE
can't get TMS to load

### ISSUE THREAD

**Issue by d3netxer** [minorua/TileLayerPlugin#8]
here is my layer definition:
dhaka_w	none	http://hiu-maps.net/hot/1.0.0/dhaka-23oct2014-flipped/{z}/{x}/{y}.png	0	2	22	20	21	90	91

I get this error when I try to add it:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/vagrant/.qgis2/python/plugins/TileLayerPlugin/tilelayerplugin.py", line 119, in run
    layer = TileLayer(self, serviceInfo, creditVisibility)
  File "/home/vagrant/.qgis2/python/plugins/TileLayerPlugin/tilelayer.py", line 76, in __init__
    self.setExtent(BoundingBox.degreesToMercatorMeters(layerDef.bbox).toQgsRectangle())
  File "/home/vagrant/.qgis2/python/plugins/TileLayerPlugin/tiles.py", line 60, in degreesToMercatorMeters
    xmax, ymax = degreesToMercatorMeters(bbox.xmax, bbox.ymax)
  File "/home/vagrant/.qgis2/python/plugins/TileLayerPlugin/tiles.py", line 39, in degreesToMercatorMeters
    y = R * math.log(math.tan((90 + lat) * math.pi / 360))
ValueError: math domain error

Python version:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

QGIS version:
2.4.0-Chugiak Chugiak, exported

Python path: ['/usr/share/qgis/python/plugins/processing', '/usr/share/qgis/python', u'/home/vagrant/.qgis2/python', u'/home/vagrant/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/home/vagrant/.qgis2/python/plugins/MetaSearch/ext-libs', '/usr/share/qgis/python/plugins/fTools/tools', '/home/vagrant/ittc1/dhaka_e_05nov14_WV2']

**Comment by minorua** [comment]
Parameters of bounding box are, in the order, `xmin ymin xmax ymax`.
